---

name: Test

on:
  workflow_call:

permissions:
  contents: read
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      # TODO: Use this instead of everything that follows once version parsing issue is resolved:
      # https://github.com/astral-sh/ruff-action/issues/256
      # - uses: astral-sh/ruff-action@v3

      # - uses: astral-sh/ruff-action@v3
      #   with:
      #     args: format --diff

      - run: pipx install poetry

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'poetry'

      - run: poetry install --no-interaction

      - run: poetry run ruff check --output-format=github

      - run: poetry run ruff format --diff

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - run: pipx install poetry

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'poetry'

      - run: poetry install --no-interaction

      - run: poetry run pytest --junitxml=junit/test-results.xml --cov=server --cov-report=xml:coverage.xml

      - uses: MishaKav/pytest-coverage-comment@v1
        with:
          pytest-xml-coverage-path: coverage.xml
          junitxml-path: junit/test-results.xml

      - name: Upload pytest results
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: pytest-results
          path: junit/test-results.xml
